CREATE TABLE IF NOT EXISTS sensor_readings (
  id BIGSERIAL PRIMARY KEY,
  timestamp BIGINT NOT NULL,
  temperature DOUBLE PRECISION NOT NULL,
  pressure DOUBLE PRECISION NOT NULL,
  humidity DOUBLE PRECISION NOT NULL,
  oxidised DOUBLE PRECISION NOT NULL,
  reduced DOUBLE PRECISION NOT NULL,
  nh3 DOUBLE PRECISION NOT NULL,
  pm1 DOUBLE PRECISION NOT NULL,
  pm2 DOUBLE PRECISION NOT NULL,
  pm10 DOUBLE PRECISION NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sensor_readings_timestamp ON sensor_readings(timestamp DESC);
