name: Build and deploy Enviro Station to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: envirostation
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '18.x'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    environment: 'Production'

    env:
      REACT_APP_INSIGHTS_API: ${{ vars.REACT_APP_INSIGHTS_API }}
      REACT_APP_REALTIME_STREAM: ${{ vars.REACT_APP_REALTIME_STREAM }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: npm install, build, and test
        run: |
          cd dashboard
          npm install
          npm run build --if-present

      - name: List directory content
        run: ls -la dashboard/build/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: dashboard/build/

      - name: List directory content
        run: ls -la dashboard/build/

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4D40A20430A44406BA7FBAB0E099CAAD }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
